### ISSUE TITLE
Missing link to Github

### ISSUE THREAD

**Issue by kpym** [ronilan/BlockLike#14]
When we are on [blocklike.org](https://www.blocklike.org) or in the [Doc](https://www.blocklike.org/docs), there is no obvious way to see that the project is open source hosted on github. I finally found a link to this repository in the FAQ section.

It would be nice to have an easier way to find this link: 
- maybe [Github corner](https://github.com/tholman/github-corners)?
- or just a link in the footer, next to "FAQ", "Docs" and "Examples"?

In any case, thanks for this project! 🙏

**Comment by ronilan** [comment]
Added to bottom of homepage.
Thanks for the heads up.
