### ISSUE TITLE
Problem with ask and KeyPressed

### ISSUE THREAD

**Issue by theudba1d** [ronilan/BlockLike#26]
Hello,

I'm working on a small game with BlockLike, which is by the way a great framework—I love it.

In my code, I have an option:

```
NomDuSprite.whenKeyPressed("a", () => {  
  if(SpriteActif == true) {
    // some action
  }
});
```

So if `SpriteActif` is `false`, the `whenKeyPressed` does nothing.

In another part of my code, I want to use:

`answer = this.ask('blabla');`

The problem is that the "a" key, because it's linked to `whenKeyPressed`, doesn't work.

Can I write in the `ask` while having a `KeyPressed`?

Thanks.

**Comment by ronilan** [comment]
Thanks for pointing this out.

As of [version 1.0.6](https://github.com/ronilan/BlockLike/releases/tag/v1.0.6) a whenKeyPressed event captures all input including that which should be only inside the ask box. 

The following code does not allow the character `a` to be input into the ask box:

```
let stage = new blockLike.Stage()
let sprite = new blockLike.Sprite()

sprite.addTo(stage)

sprite.whenFlag(() => {
  answer = sprite.ask('What\'s your name?')
})

sprite.whenKeyPressed("a", () => {
  this.say("a pressed")
})
 ```

code fix to the library will be required.

**Comment by ronilan** [comment]
### Issue Resolution

Version [1.0.7](https://www.npmjs.com/package/blocklike/v/1.0.7) resolves the issue. See: https://github.com/ronilan/BlockLike/commit/e4364c3949230b97f8268e54c16c9c88205a0e80

### Example Usage

Blow is example of how to properly used the keypress event listener in and the ask input box at the same time. Interactive version at: https://www.blocklike.org/example/03-events/whenkeypressed_ask 
```
    const stage = new blockLike.Stage()
    const sprite = new blockLike.Sprite()

    let asking = false
    let answer = ''
    
    sprite.addTo(stage)

    sprite.say('Click me OR Press "a"')

    sprite.whenClicked(() => {
      asking = true
      answer = sprite.ask('What\'s your name?')
      asking = false
      this.say(`Your name is: ${answer}`)
    })

    sprite.whenKeyPressed('a', () => {
      if (!asking) {
        this.say('a')
        this.changeY(100)
        this.wait(0.5)
        this.changeY(-100)
        this.say('')
      }
    })
```

Thanks [theudba1d](https://github.com/theudba1d) 🏆
